spring.datasource.url=jdbc:h2:file:./data/events-db;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

provider.events-url= ${PROVIDER_URL:http://localhost:${server.port:8080}/mock-provider/events}
provider.refresh-rate-ms=30000

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
